# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Piou.io
email: gilles.piou@gmail.com
description: A developer blog covering front-end techniques, CSS, JavaScript.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.piou.io" # the base hostname & protocol for your site
twitter_username: pioug
github_username: pioug

# Build settings
markdown: kramdown
exclude: ['node_modules', 'gulpfile.js', 'package.json']

permalink: "/:title"
